#define CATCH_CONFIG_MAIN  // This tells Catch to provide a main() - only do this in one cpp file
#define BOOST_BIND_GLOBAL_PLACEHOLDERS //is this wanted? It disables a boost warning probably generated by catch2.

#include <catch2/catch.hpp>
#include "TestNode.hpp"
#include "TestNodeStorage.hpp"
#include "TestIntegralTemplatedTupleAlloc.hpp"