name: Publish Conan branch package

on: [ push ]

concurrency:
  group: publish-conan-branch-package-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-conan-branch-package:
    uses: dice-group/cpp-conan-release-reusable-workflow/.github/workflows/publish-conan-branch-package.yml@v2.0.2
    with:
      public_artifactory: true
      os: ubuntu-24.04
      compiler: clang-19
      cmake-version: 3.30.5
      conan-version: 2.30.0
      conan-options: -o boost/*:header_only=True
    secrets:
      CONAN_CICD_USERNAME: ${{ secrets.CONAN_CICD_USERNAME }}
      CONAN_CICD_PASSWORD: ${{ secrets.CONAN_CICD_PASSWORD }}
      CONAN_CICD_ENDPOINT: ${{ secrets.CONAN_CICD_ENDPOINT }}