name: release

on:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Get the Ref
        id: get-ref
        uses: ankitvgupta/ref-to-tag-action@master
        with:
          ref: ${{ github.ref }}
          head_ref: ${{ github.head_ref }}
      - name: Cache conan, pip and libtorch files
        uses: actions/cache@v2
        with:
          path: |
            ~/.conan/data
            ~/.cache/pip
            ~/.cache/libtorch
          key: ${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Install packages
        run: scripts/install.sh
      - name: Prepare environment
        run: scripts/prepare.sh Release
      - name: Build
        run: scripts/build.sh Release
      - name: Run tests
        run: scripts/test.sh
      - name: Upload test log
        uses: actions/upload-artifact@v2
        with:
          name: tests.log.xz
          path: tests.log.xz
