name: release

on:
  push:
    branches:
      - master
      - development
    tags:
      - '*'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Get the Ref
        id: get-ref
        uses: ankitvgupta/ref-to-tag-action@master
        with:
          ref: ${{ github.ref }}
          head_ref: ${{ github.head_ref }}
      - name: Cache conan, pip and libtorch files
        uses: actions/cache@v2
        with:
          path: |
            ~/.conan/data
            ~/.cache/pip
            ~/.cache/libtorch
          key: ${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Install packages
        run: scripts/install.sh
      - name: Prepare environment
        run: scripts/prepare.sh Release
      - name: Build
        run: scripts/build.sh Release
      - name: Release
        run: scripts/release.sh Release "" "" ${{ steps.get-ref.outputs.tag }}
        env:
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
