name: release

on:
  push:
    branches:
      - master
      - development
    tags:
      - '*'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Get the Ref
        id: get-ref
        uses: ankitvgupta/ref-to-tag-action@master
        with:
          ref: ${{ github.ref }}
          head_ref: ${{ github.head_ref }}
      - name: Enable apt package cache
        run: echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' | sudo tee /etc/apt/apt.conf.d/50-cache
      - name: Cache apt, conan and pip files
        uses: actions/cache@v2
        with:
          path: |
            /var/cache/apt
            ~/.conan/data
            ~/.cache/pip
          key: ${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Install packages
        run: scripts/install.sh
      - name: Prepare environment
        run: scripts/prepare.sh
      - name: Build
        run: scripts/build.sh
      - name: Release
        run: scripts/release.sh ${{ steps.get-ref.outputs.tag }}
